version: '3'

services:
  xuntos-auth:
    image: xuntos-auth
    build:
      context: .
    ports:
      - 3000:3000
    depends_on:
      - database
    environment:
      XUNTOS_AUTH_DATABASE_URI: mongodb://xuntos:xuntos@database:27017/xuntos-auth

  database:
    image: mongo:4.4
    ports:
      - 27017-27019:27017-27019
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - database-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: xuntos
      MONGO_INITDB_ROOT_PASSWORD: xuntos
      MONGO_INITDB_DATABASE: xuntos-auth


volumes:
  database-data:
