name: Continuous Integration
on:
  - push
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.15
      - run: make install
      - run: make lint
      - run: make tests
